"""Print the PostgreSQL schema (tables, indexes, Row Level Security) for Supabase.

    python -m scripts.export_schema > ../supabase/migrations/<timestamp>_<name>.sql

The DDL is generated from the SQLAlchemy models, so the Supabase schema can never
drift from what the backend expects.
"""

from __future__ import annotations

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from app.models import Base

# Tables that only the backend (service role) may touch - no client policies at all.
SERVER_ONLY = {"app_secrets", "audit_logs"}

HEADER = """-- NEXUS schema for Supabase / PostgreSQL.
-- Generated by `python -m scripts.export_schema` from backend/app/models - do not edit by hand.
--
-- The backend connects with a privileged role (DATABASE_URL) and scopes every
-- query to the authenticated user itself. Row Level Security is defence in
-- depth: if anything ever talks to these tables through the Supabase client API
-- with a user's token, it can only see that user's rows. Server-only tables
-- (secrets, audit log) have RLS enabled with no policies, i.e. no client access.
"""


def build() -> str:
    dialect = postgresql.dialect()
    out = [HEADER, "BEGIN;\n"]
    for table in Base.metadata.sorted_tables:
        out.append(str(CreateTable(table, if_not_exists=True).compile(dialect=dialect)).strip() + ";")
        for idx in sorted(table.indexes, key=lambda i: i.name or ""):
            out.append(str(CreateIndex(idx, if_not_exists=True).compile(dialect=dialect)).strip() + ";")
        out.append("")
    out.append("-- Row Level Security ----------------------------------------------------")
    for table in Base.metadata.sorted_tables:
        name = table.name
        out.append(f"ALTER TABLE {name} ENABLE ROW LEVEL SECURITY;")
        if name in SERVER_ONLY:
            continue
        owner = "id" if name == "users" else "user_id"
        out.append(f"DROP POLICY IF EXISTS {name}_owner ON {name};")
        out.append(
            f"CREATE POLICY {name}_owner ON {name} FOR ALL TO authenticated "
            f"USING ({owner} = auth.uid()) WITH CHECK ({owner} = auth.uid());"
        )
    out.append("\nCOMMIT;\n")
    return "\n".join(out)


if __name__ == "__main__":
    print(build())
