-- NEXUS schema for Supabase / PostgreSQL.
-- Generated by `python -m scripts.export_schema` from backend/app/models - do not edit by hand.
--
-- The backend connects with a privileged role (DATABASE_URL) and scopes every
-- query to the authenticated user itself. Row Level Security is defence in
-- depth: if anything ever talks to these tables through the Supabase client API
-- with a user's token, it can only see that user's rows. Server-only tables
-- (secrets, audit log) have RLS enabled with no policies, i.e. no client access.

BEGIN;

CREATE TABLE IF NOT EXISTS app_secrets (
	name VARCHAR(80) NOT NULL, 
	ciphertext VARCHAR(4096) NOT NULL, 
	hint VARCHAR(16) NOT NULL, 
	updated_by UUID, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS audit_logs (
	user_id UUID, 
	event VARCHAR(60) NOT NULL, 
	detail JSONB NOT NULL, 
	ip VARCHAR(64), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_audit_logs_user_created ON audit_logs (user_id, created_at);

CREATE TABLE IF NOT EXISTS users (
	email VARCHAR(320), 
	display_name VARCHAR(120), 
	auth_provider VARCHAR(20) NOT NULL, 
	is_admin BOOLEAN NOT NULL, 
	last_seen_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS agent_runs (
	user_id UUID NOT NULL, 
	conversation_id UUID, 
	request_id VARCHAR(64), 
	agent VARCHAR(40) NOT NULL, 
	task TEXT NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	summary TEXT, 
	error JSONB, 
	metadata JSONB NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_agent_runs_request_id ON agent_runs (request_id);
CREATE INDEX IF NOT EXISTS ix_agent_runs_user_started ON agent_runs (user_id, started_at);

CREATE TABLE IF NOT EXISTS automations (
	user_id UUID NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	kind VARCHAR(24) NOT NULL, 
	trigger_type VARCHAR(12) NOT NULL, 
	schedule JSONB NOT NULL, 
	timezone VARCHAR(64) NOT NULL, 
	config JSONB NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	next_run_at TIMESTAMP WITH TIME ZONE, 
	last_run_at TIMESTAMP WITH TIME ZONE, 
	last_result JSONB NOT NULL, 
	run_count INTEGER NOT NULL, 
	failure_count INTEGER NOT NULL, 
	locked_until TIMESTAMP WITH TIME ZONE, 
	locked_by VARCHAR(64), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_automations_due ON automations (status, next_run_at);
CREATE INDEX IF NOT EXISTS ix_automations_user_id ON automations (user_id);

CREATE TABLE IF NOT EXISTS conversations (
	user_id UUID NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	archived BOOLEAN NOT NULL, 
	metadata JSONB NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_conversations_user_id ON conversations (user_id);

CREATE TABLE IF NOT EXISTS devices (
	user_id UUID NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	platform VARCHAR(120), 
	fingerprint VARCHAR(128), 
	capabilities JSONB NOT NULL, 
	last_seen_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_devices_fingerprint ON devices (fingerprint);
CREATE INDEX IF NOT EXISTS ix_devices_user_id ON devices (user_id);

CREATE TABLE IF NOT EXISTS files (
	user_id UUID NOT NULL, 
	filename VARCHAR(255) NOT NULL, 
	stored_name VARCHAR(80) NOT NULL, 
	mime_type VARCHAR(100) NOT NULL, 
	kind VARCHAR(12) NOT NULL, 
	size_bytes INTEGER NOT NULL, 
	sha256 VARCHAR(64) NOT NULL, 
	status VARCHAR(12) NOT NULL, 
	page_count INTEGER, 
	char_count INTEGER, 
	error TEXT, 
	metadata JSONB NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_files_user_id ON files (user_id);

CREATE TABLE IF NOT EXISTS memories (
	user_id UUID NOT NULL, 
	category VARCHAR(20) NOT NULL, 
	subject VARCHAR(200) NOT NULL, 
	value TEXT NOT NULL, 
	aliases JSONB NOT NULL, 
	attributes JSONB NOT NULL, 
	source VARCHAR(16) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	sensitivity VARCHAR(16) NOT NULL, 
	confidence FLOAT NOT NULL, 
	use_count INTEGER NOT NULL, 
	last_used_at TIMESTAMP WITH TIME ZONE, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_memories_user_category ON memories (user_id, category);
CREATE INDEX IF NOT EXISTS ix_memories_user_id ON memories (user_id);

CREATE TABLE IF NOT EXISTS notifications (
	user_id UUID NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	body TEXT NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	status VARCHAR(10) NOT NULL, 
	automation_id UUID, 
	data JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	read_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_notifications_user_status ON notifications (user_id, status, created_at);

CREATE TABLE IF NOT EXISTS permission_grants (
	user_id UUID NOT NULL, 
	tool VARCHAR(60) NOT NULL, 
	scope VARCHAR(500) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_used_at TIMESTAMP WITH TIME ZONE, 
	use_count INTEGER NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_permission_grants_user_id ON permission_grants (user_id);

CREATE TABLE IF NOT EXISTS permission_requests (
	user_id UUID NOT NULL, 
	request_id VARCHAR(64), 
	tool VARCHAR(60) NOT NULL, 
	agent VARCHAR(40), 
	risk_level VARCHAR(10) NOT NULL, 
	summary TEXT NOT NULL, 
	reason TEXT, 
	details JSONB NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	decision VARCHAR(16), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	decided_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_permission_requests_user_id ON permission_requests (user_id);

CREATE TABLE IF NOT EXISTS tasks (
	user_id UUID NOT NULL, 
	title VARCHAR(300) NOT NULL, 
	notes TEXT, 
	status VARCHAR(16) NOT NULL, 
	priority VARCHAR(10) NOT NULL, 
	due_at TIMESTAMP WITH TIME ZONE, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	automation_id UUID, 
	source VARCHAR(16) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_tasks_user_status_due ON tasks (user_id, status, due_at);

CREATE TABLE IF NOT EXISTS tool_calls (
	user_id UUID NOT NULL, 
	agent_run_id UUID, 
	request_id VARCHAR(64), 
	agent VARCHAR(40), 
	tool VARCHAR(60) NOT NULL, 
	arguments JSONB NOT NULL, 
	risk_level VARCHAR(10) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	approval VARCHAR(16) NOT NULL, 
	result_summary TEXT, 
	error JSONB, 
	duration_ms INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_tool_calls_agent_run_id ON tool_calls (agent_run_id);
CREATE INDEX IF NOT EXISTS ix_tool_calls_user_created ON tool_calls (user_id, created_at);

CREATE TABLE IF NOT EXISTS user_preferences (
	user_id UUID NOT NULL, 
	key VARCHAR(80) NOT NULL, 
	value JSONB NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_user_preferences_user_key UNIQUE (user_id, key), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_user_preferences_user_id ON user_preferences (user_id);

CREATE TABLE IF NOT EXISTS automation_runs (
	automation_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	condition_met BOOLEAN, 
	result JSONB NOT NULL, 
	error JSONB, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(automation_id) REFERENCES automations (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_automation_runs_automation_id ON automation_runs (automation_id);
CREATE INDEX IF NOT EXISTS ix_automation_runs_user_id ON automation_runs (user_id);

CREATE TABLE IF NOT EXISTS file_chunks (
	file_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	idx INTEGER NOT NULL, 
	text TEXT NOT NULL, 
	section VARCHAR(300), 
	page INTEGER, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(file_id) REFERENCES files (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_file_chunks_file_idx ON file_chunks (file_id, idx);
CREATE INDEX IF NOT EXISTS ix_file_chunks_user_id ON file_chunks (user_id);

CREATE TABLE IF NOT EXISTS messages (
	conversation_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	role VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	request_id VARCHAR(64), 
	attachments JSONB NOT NULL, 
	actions JSONB NOT NULL, 
	sources JSONB NOT NULL, 
	metadata JSONB NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES conversations (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_messages_conversation_created ON messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS ix_messages_request_id ON messages (request_id);
CREATE INDEX IF NOT EXISTS ix_messages_user_id ON messages (user_id);

-- Row Level Security ----------------------------------------------------
ALTER TABLE app_secrets ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS users_owner ON users;
CREATE POLICY users_owner ON users FOR ALL TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS agent_runs_owner ON agent_runs;
CREATE POLICY agent_runs_owner ON agent_runs FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE automations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS automations_owner ON automations;
CREATE POLICY automations_owner ON automations FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS conversations_owner ON conversations;
CREATE POLICY conversations_owner ON conversations FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS devices_owner ON devices;
CREATE POLICY devices_owner ON devices FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS files_owner ON files;
CREATE POLICY files_owner ON files FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE memories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS memories_owner ON memories;
CREATE POLICY memories_owner ON memories FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS notifications_owner ON notifications;
CREATE POLICY notifications_owner ON notifications FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE permission_grants ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS permission_grants_owner ON permission_grants;
CREATE POLICY permission_grants_owner ON permission_grants FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE permission_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS permission_requests_owner ON permission_requests;
CREATE POLICY permission_requests_owner ON permission_requests FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tasks_owner ON tasks;
CREATE POLICY tasks_owner ON tasks FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE tool_calls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tool_calls_owner ON tool_calls;
CREATE POLICY tool_calls_owner ON tool_calls FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_preferences_owner ON user_preferences;
CREATE POLICY user_preferences_owner ON user_preferences FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE automation_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS automation_runs_owner ON automation_runs;
CREATE POLICY automation_runs_owner ON automation_runs FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE file_chunks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS file_chunks_owner ON file_chunks;
CREATE POLICY file_chunks_owner ON file_chunks FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS messages_owner ON messages;
CREATE POLICY messages_owner ON messages FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

COMMIT;

